In [261]:
#Gradient Ascent with Steepest size(Quadratic function)
import numpy as np
import matplotlib.pyplot as plt
def f(x):
    x1= x[0].item()
    x2= x[1].item()
    x3= x[2].item()
    y= -1/2*(3*x1**2+4*x2**2+3*x3**2+4*x2*x3+2*x1*x3)+(1*x1+2*x2+2*x3)
    return y

def grad_f(x):
    x1= x[0].item()
    x2= x[1].item()
    x3= x[2].item()
    g= np.zeros((3,1))
    g[0] = -(3*x1+x3-1)
    g[1] = -(4*x2+2*x3-2)
    g[2] = -(x1+2*x2+3*x3-2)
    return g

Q = np.array([3,0,1,0,4,2,1,2,3]).reshape(3,3)
b = np.array([1,2,2]).reshape(3,1)

eps0 = 1e-3
stepsize = 1e-1
stop=False
itera=0
x0 = np.array([1,1,1]).reshape(3,1)
x = np.zeros((3,1))

while not stop:
    g = grad_f(x0)
    stepsize = (g.T@g)/(g.T@Q@g)#steepest size
    x = x0 + stepsize*g
    if np.linalg.norm(x-x0)/np.linalg.norm(x0)<eps0:
        stop=True
        break
    x0 =x
    itera+=1
print("argmax x: ", x, "iteration: ", itera)
print(np.linalg.inv(Q)@b)
print(f(x))

argmax x:  [[0.20027048]
 [0.30029911]
 [0.39934748]] iteration:  14
[[0.2]
 [0.3]
 [0.4]]
0.799999639494876


In [262]:
#Conjugate Gradient Ascent(Quadratic function)
import numpy as np
import matplotlib.pyplot as plt
def f(x):
    x1= x[0].item()
    x2= x[1].item()
    x3= x[2].item()
    y= -1/2*(3*x1**2+4*x2**2+3*x3**2+4*x2*x3+2*x1*x3)+(1*x1+2*x2+2*x3)
    return y

def grad_f(x):
    x1= x[0].item()
    x2= x[1].item()
    x3= x[2].item()
    g= np.zeros((3,1))
    g[0] = -(3*x1+x3-1)
    g[1] = -(4*x2+2*x3-2)
    g[2] = -(x1+2*x2+3*x3-2)
    return g

Q = np.array([3,0,1,0,4,2,1,2,3]).reshape(3,3)
b = np.array([1,2,2]).reshape(3,1)

eps0 = 1e-3
stepsize = 1e-1
stop=False
itera=0
beta = 0
x0 = np.array([1,1,1]).reshape(3,1)
x = np.zeros((3,1))
g=grad_f(x0)
g_up = np.zeros((3,1))
d=g
d_up = np.zeros((3,1))

while not stop:
    stepsize = (g.T@d)/(d.T@Q@d)
    x = x0 + stepsize*d
    g_up=grad_f(x)
    beta = (g_up.T@Q@d)/(d.T@Q@d)
    d_up = -g_up+beta*d
    d=d_up
    g=g_up
    if np.linalg.norm(x-x0)/np.linalg.norm(x0)<eps0:
        stop=True
        break
    x0 =x
    itera+=1
print("argmax x: ", x, "iteration: ", itera)
print(np.linalg.inv(Q)@b)
print(f(x))

argmax x:  [[0.2]
 [0.3]
 [0.4]] iteration:  3
[[0.2]
 [0.3]
 [0.4]]
0.8


In [264]:
#Gradient Descent with Newton's Method(Quadratic function)
import numpy as np
import matplotlib.pyplot as plt
def f(x):
    x1= x[0].item()
    x2= x[1].item()
    x3= x[2].item()
    y= 1/2*(3*x1**2+4*x2**2+3*x3**2+4*x2*x3+2*x1*x3)-(1*x1+2*x2+2*x3)
    return y

def grad_f(x):
    x1= x[0].item()
    x2= x[1].item()
    x3= x[2].item()
    g= np.zeros((3,1))
    g[0] = 3*x1+x3-1
    g[1] = 4*x2+2*x3-2
    g[2] = x1+2*x2+3*x3-2
    return g

Q = np.array([3,0,1,0,4,2,1,2,3]).reshape(3,3)
b = np.array([1,2,2]).reshape(3,1)

eps0 = 1e-3
stepsize = 1e-1
stop=False
itera=0
x0 = np.array([1,1,1]).reshape(3,1)
x = np.zeros((3,1))

while not stop:
    g = grad_f(x0)
    x = x0 - np.linalg.inv(Q)@g
    if np.linalg.norm(x-x0)/np.linalg.norm(x0)<eps0:
        stop=True
        break
    x0 =x
    itera+=1
print("argmin x: ", x, "iteration: ", itera)
print(np.linalg.inv(Q)@b)
print(f(x))

argmin x:  [[0.2]
 [0.3]
 [0.4]] iteration:  1
[[0.2]
 [0.3]
 [0.4]]
-0.8


In [265]:
#Gradient Ascent with Quasi-Newton Method(Quadratic function)
import numpy as np
import matplotlib.pyplot as plt
def f(x):
    x1= x[0].item()
    x2= x[1].item()
    x3= x[2].item()
    y= -1/2*(3*x1**2+4*x2**2+3*x3**2+4*x2*x3+2*x1*x3)+(1*x1+2*x2+2*x3)
    return y

def grad_f(x):
    x1= x[0].item()
    x2= x[1].item()
    x3= x[2].item()
    g= np.zeros((3,1))
    g[0] = -(3*x1+x3-1)
    g[1] = -(4*x2+2*x3-2)
    g[2] = -(x1+2*x2+3*x3-2)
    return g

Q = np.array([3,0,1,0,4,2,1,2,3]).reshape(3,3)
b = np.array([1,2,2]).reshape(3,1)

eps0 = 1e-3
stepsize = 1e-1
stop=False
itera=0
x0 = np.array([1,1,1]).reshape(3,1)
x = np.zeros((3,1))
d = np.zeros((3,1))
H0 = np.identity(3) 
H_up = np.identity(3)
g = np.zeros((3,1))
g_up = np.zeros((3,1))
s = np.zeros((3,1))#delta theta
y = np.zeros((3,1))#delta gradient

while not stop:
    g = grad_f(x0)
    d = H0@g
    stepsize = (g.T@d)/(d.T@Q@d)
    x = x0 + stepsize*d
    s = x-x0
    g_up = grad_f(x)
    y = g_up-g
    H = (np.identity(3)-(s@y.T)/(s.T@y))@H0@(np.identity(3)-(y@s.T)/(s.T@y))+(s@s.T)/(s.T@y)
    if np.linalg.norm(x-x0)/np.linalg.norm(x0)<eps0 or np.linalg.norm(g_up)==0:
        stop=True
        break
    x0 = x
    H0 = H
    itera+=1
print("argmax x: ", x, "iteration: ", itera)
print(np.linalg.inv(Q)@b)
print(f(x))

argmax x:  [[0.2]
 [0.3]
 [0.4]] iteration:  3
[[0.2]
 [0.3]
 [0.4]]
0.8


In [260]:
#Conjugate Gradient Ascent(General function)
import numpy as np
import matplotlib.pyplot as plt
def f(x):
    x1= x[0].item()
    x2= x[1].item()
    x3= x[2].item()
    y= -1/2*(3*x1**2+4*x2**2+3*x3**2+4*x2*x3+2*x1*x3)+(1*x1+2*x2+2*x3)
    return y

def grad_f(x):
    x1= x[0].item()
    x2= x[1].item()
    x3= x[2].item()
    g= np.zeros((3,1))
    g[0] = -(3*x1+x3-1)
    g[1] = -(4*x2+2*x3-2)
    g[2] = -(x1+2*x2+3*x3-2)
    return g

Q = np.array([3,0,1,0,4,2,1,2,3]).reshape(3,3)
b = np.array([1,2,2]).reshape(3,1)

eps0 = 1e-3
stepsize = 1e-1
stop=False
itera=0
beta = 0
x0 = np.array([1,1,1]).reshape(3,1)
x = np.zeros((3,1))
g=grad_f(x0)
g_up = np.zeros((3,1))
d=g
d_up = np.zeros((3,1))

while not stop:
    stepsize = (g.T@d)/(d.T@Q@d)
    x = x0 + stepsize*d
    g_up=grad_f(x)
    #beta = (g_up.T@(g_up-g))/(d.T@(g_up-g))#Hestenes-Stiefel
    #beta = (g_up.T@(g_up-g))/(g.T@g) #Polak-Ribiere
    beta = (g_up.T@g_up)/(g.T@g) #Fletcher-Reeves
    d_up = -g_up+beta*d
    d=d_up
    g=g_up
    if np.linalg.norm(x-x0)/np.linalg.norm(x0)<eps0:
        stop=True
        break
    x0 =x
    itera+=1
print("argmin x: ", x, "iteration: ", itera)
print(np.linalg.inv(Q)@b)
print(f(x))

argmin x:  [[0.19995576]
 [0.29994943]
 [0.40003872]] iteration:  7
[[0.2]
 [0.3]
 [0.4]]
0.7999999953301581
